apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-demo-app
  namespace: default
spec:
  replicas: 2 # Levantaremos 2 contenedores para alta disponibilidad
  selector:
    matchLabels:
      app: devsecops-demo
  template:
    metadata:
      labels:
        app: devsecops-demo
    spec:
      containers:
        - name: fastapi-app
          # REEMPLAZA "jinnso/devsecops-pipeline" por el nombre exacto de tu repo si es distinto
          image: ghcr.io/jinnso/devsecops-pipeline/myapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          # Probes de DevSecOps/SRE (Verifican la salud de la app)
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
