apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-service
  namespace: default
spec:
  selector:
    app: devsecops-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 # El puerto que expusimos en nuestro Dockerfile
  type: ClusterIP # Solo accesible dentro del clúster por ahora