apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo-service
  namespace: default
spec:
  selector:
    app: devsecops-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000 # El puerto que expusimos en nuestro Dockerfile
  type: LoadBalancer # Solo accesible dentro del clúster por ahora(CLusterIP) #2 Cambiado a LoadBalancer para prueba de app y argocd